---
- name: Install Apache + mod_php and deploy single-file PHP app (all-in-one)
  hosts: webserver
  become: yes
  vars:
    index_path: /var/www/html/index.php
    success_marker: "APPLICATION_INSTALL_SUCCESS"
    db_host: "192.168.100.151"
    db_name: "lampdb"
    db_user: "lampuser"
    db_password: "lamppass"
    php_pkg: "php8.3"
    libapache_php_pkg: "libapache2-mod-php8.3"
    php_mysql_pkg: "php8.3-mysql"

  tasks:
    - name: Refresh apt cache
      apt:
        update_cache: yes
        cache_valid_time: 3600

    - name: Install Apache + mod_php + php-mysql
      apt:
        name:
          - apache2
          - "{{ php_pkg }}"
          - "{{ libapache_php_pkg }}"
          - "{{ php_mysql_pkg }}"
        state: present

    - name: Remove default Apache index.html (if present)
      file:
        path: /var/www/html/index.html
        state: absent

    - name: Ensure mpm_event is disabled (switch to prefork for mod_php)
      ansible.builtin.shell: |
        # disable event, enable prefork and php mod
        a2dismod mpm_event || true
        a2enmod mpm_prefork || true
        a2enmod php8.3 || true
      args:
        warn: false
      register: mods_enable
      changed_when: mods_enable.rc == 0
      failed_when: false
      notify: Restart apache

    - name: Ensure apache2 is started and enabled
      service:
        name: apache2
        state: started
        enabled: yes

    - name: Deploy index.php (inline template)
      ansible.builtin.template:
        dest: "{{ index_path }}"
        owner: www-data
        group: www-data
        mode: '0644'
        content: |
          <?php
          $db_host = "{{ db_host }}";
          $db_user = "{{ db_user }}";
          $db_pass = "{{ db_password }}";
          $db_name = "{{ db_name }}";

          function esc($s){ return htmlspecialchars($s, ENT_QUOTES, 'UTF-8'); }

          echo "<!doctype html><html><head><meta charset='utf-8'><title>Simple LAMP App</title></head><body>";
          echo "<h1>Simple LAMP App</h1>";
          echo "<p>Server date/time: " . date('Y-m-d H:i:s') . "</p>";

          $conn = @new mysqli($db_host, $db_user, $db_pass, $db_name);

          if ($conn->connect_error) {
              echo "<div style='color:red;'>Database connection failed.</div>";
          } else {
              $result = @$conn->query('SELECT NOW() AS now_ts');
              if ($result && $row = $result->fetch_assoc()) {
                  echo "<div style='color:green;'>Connected to MySQL at " . esc($db_host) . "</div>";
                  echo "<p>Database current time: " . esc($row['now_ts']) . "</p>";
                  $result->free();
              } else {
                  echo "<div style='color:orange;'>DB connected but query failed.</div>";
              }
              $conn->close();
          }

          echo "<div>Application installed successfully — {{ success_marker }}</div>";
          echo "</body></html>";
      notify: Restart apache

    - name: Ensure php modules and apache are ready (quick reload)
      service:
        name: apache2
        state: reloaded

  handlers:
    - name: Restart apache
      service:
        name: apache2
        state: restarted
