---
- name: Install Apache + PHP-FPM and deploy app page
  hosts: webserver
  become: yes
  vars:
    index_path: /var/www/html/index.php
    success_marker: "APPLICATION_INSTALL_SUCCESS"
    php_fpm_conf_path: /etc/apache2/conf-available/php-fpm.conf
    php_fpm_socket: /run/php/php8.3-fpm.sock
    db_host: 192.168.100.151       
    db_name: lampdb
    db_user: lampuser
    db_password: lamppass
  tasks:
    - name: Install Apache and PHP packages
      apt:
        name:
          - apache2
          - php
          - php-mysql
          - php8.3-fpm
        state: present

    - name: Enable Apache modules required for PHP-FPM
      ansible.builtin.shell: |
        a2enmod proxy proxy_fcgi setenvif || true
        a2dismod php8.3 || true
      args:
        warn: false
      register: apache_mods
      changed_when: >
        apache_mods.stdout is defined and
        ( 'enabled' in apache_mods.stdout.lower() or
          'already enabled' not in apache_mods.stdout.lower() ) 
      failed_when: false

    - name: Create php-fpm Apache config
      copy:
        dest: "{{ php_fpm_conf_path }}"
        content: |
          <IfModule proxy_fcgi_module>
              <FilesMatch \.php$>
                  SetHandler "proxy:unix:{{ php_fpm_socket }}|fcgi://localhost/"
              </FilesMatch>
          </IfModule>
      notify: Reload apache

    - name: Enable php-fpm Apache config
      ansible.builtin.shell: a2enconf php-fpm || true
      args:
        warn: false
      register: a2enconf_out
      changed_when: "'enabled' in (a2enconf_out.stdout | default(''))"
      failed_when: false

    - name: Deploy index.php with DB connection and success marker
      copy:
        dest: /var/www/html/index.php
        content: |
          <?php
          $db_host = "{{ db_host | default('192.168.100.151') }}";
          $db_user = "{{ db_user | default('lampuser') }}";
          $db_pass = "{{ db_password | default('lamppass') }}";
          $db_name = "{{ db_name | default('lampdb') }}";
    
          function show($s){ echo htmlspecialchars($s); }
    
          echo "<!doctype html><html><head><meta charset='utf-8'><title>Simple LAMP App</title></head><body>";
          echo "<h1>Simple LAMP App</h1>";
          echo "<p>Server date/time: " . date('Y-m-d H:i:s') . "</p>";
    
          $conn = @new mysqli($db_host, $db_user, $db_pass, $db_name);
          if ($conn->connect_error) {
              echo "<div style='color:red;'>Database connection failed.</div>";
          } else {
              $result = @$conn->query("SELECT NOW()");
              if ($result) {
                  $row = $result->fetch_row();
                  echo "<div style='color:green;'>Connected to MySQL at " . show($db_host) . "</div>";
                  echo "<p>Database current time: " . show($row[0]) . "</p>";
                  $result->free();
              } else {
                  echo "<div style='color:orange;'>DB connected but query failed.</div>";
              }
              $conn->close();
          }
          echo "<div>Application installed successfully — APPLICATION_INSTALL_SUCCESS</div>";
          echo "</body></html>";
        owner: www-data
        group: www-data
        mode: '0644'
      notify: Restart apache

  handlers:
    - name: Reload apache
      service:
        name: apache2
        state: reloaded

    - name: Restart apache
      service:
        name: apache2
        state: restarted
