---
- name: Install Apache + PHP and deploy app page
  hosts: webserver
  become: yes
  vars:
    index_path: /var/www/html/index.php
    success_marker: "APPLICATION_INSTALL_SUCCESS"
  tasks:
    - name: Install Apache and PHP and php-mysql
      apt:
        name:
          - apache2
          - php
          - libapache2-mod-php
          - php-mysql
        state: present

    - name: Ensure apache is enabled and started
      service:
        name: apache2
        state: started
        enabled: yes

    - name: Create idempotent PHP page showing date/time and success notification
      copy:
        dest: "{{ index_path }}"
        content: |
          <?php
          // Simple page: shows date/time and a success message with a marker to check in health_check
          echo "<html><head><title>Simple LAMP App</title></head><body>";
          echo "<h1>Simple LAMP App</h1>";
          echo "<p>Server date/time: " . date('Y-m-d H:i:s') . "</p>";
          echo "<div>Application installed successfully — {{ success_marker }}</div>";
          echo "</body></html>";
        owner: www-data
        group: www-data
        mode: '0644'

    - name: Ensure ownership of webroot
      file:
        path: /var/www/html
        owner: www-data
        group: www-data
        recurse: no

  handlers:
    - name: restart apache
      service:
        name: apache2
        state: restarted
