---
- name: Deploy workflow example web app
  hosts: webserver
  become: yes

  vars:
    app_path: "/var/www/html"
    db_host: "{{ groups['dev'][0] | default('192.168.100.151') }}"
    db_name: "myappdb"
    db_user: "appuser"
    db_pass: "AppUserPass!"
    workflow_name: "AWX Workflow Example - LAMP Deployment"

  tasks:
    - name: Ensure Apache + PHP installed
      apt:
        name:
          - apache2
          - php
          - libapache2-mod-php
          - php-mysql
        state: present
        update_cache: yes
    
    - name: Remove default Apache index.html if present
      file:
        path: /var/www/html/index.html
        state: absent
    
    - name: Deploy index.php (workflow demo page)
      copy:
        dest: /var/www/html/index.php
        mode: '0644'
        content: |
          <?php
          $db_host = "{{ db_host | default('127.0.0.1') }}";
          $db_user = "{{ db_user | default('appuser') }}";
          $db_pass = "{{ db_pass | default('AppUserPass!') }}";
          $db_name = "{{ db_name | default('myappdb') }}";
          $workflow = "{{ workflow_name | default('AWX Workflow Demo') }}";
          $hostname = gethostname();
          $timestamp = date("Y-m-d H:i:s");
    
          $conn = @new mysqli($db_host, $db_user, $db_pass, $db_name);
          $db_status = $conn->connect_error ? "❌ DB connection failed: " . $conn->connect_error : "✅ DB connected successfully";
    
          echo "<html><head><title>$workflow</title></head><body style='font-family:Arial;margin:30px;'>";
          echo "<h2 style='color:#2d89ef;'>$workflow</h2>";
          echo "<p><strong>Host:</strong> $hostname</p>";
          echo "<p><strong>DB Host:</strong> $db_host</p>";
          echo "<p><strong>DB Status:</strong> $db_status</p>";
          echo "<p><strong>Timestamp:</strong> $timestamp</p>";
          echo "<hr><small>Generated by AWX</small></body></html>";
          ?>
    
    - name: Ensure /var/www/html owned by www-data
      file:
        path: /var/www/html
        owner: www-data
        group: www-data
        recurse: yes
    
    - name: Enable PHP module (ensure libapache2-mod-php enabled)
      command: a2enmod php7.4
      args:
        warn: false
      register: enable_php
      failed_when: false
      changed_when: "'Module php7.4 already enabled' not in enable_php.stdout"
    
      # NOTE: modify php7.4 to your PHP version (php8.1 etc.) if needed.
    
    - name: Restart Apache to pick up changes
      service:
        name: apache2
        state: restarted
        enabled: yes
    
    - name: Test the site via curl on localhost
      command: curl -sS http://127.0.0.1/
      register: curl_out
      failed_when: curl_out.stdout is not search("AWX Workflow Demo")  # fail if our text isn't present
      changed_when: false
    
    - name: Show first 40 chars of page (for job output)
      debug:
        msg: "{{ curl_out.stdout[:400] | default('no output') }}"
