---
- name: Deploy workflow example web app
  hosts: webserver
  become: yes

  vars:
    app_path: "/var/www/html"
    db_host: "{{ groups['dev'][0] | default('192.168.100.151') }}"
    db_name: "myappdb"
    db_user: "appuser"
    db_pass: "AppUserPass!"
    workflow_name: "AWX Workflow Example - LAMP Deployment"

  tasks:
    - name: Install Apache, PHP and dependencies
      apt:
        name:
          - apache2
          - php
          - libapache2-mod-php
          - php-mysql
        state: present
        update_cache: yes

    - name: Ensure Apache is started and enabled
      service:
        name: apache2
        state: started
        enabled: yes

    - name: Create demo index.php page
      copy:
        dest: "{{ app_path }}/index.php"
        mode: '0644'
        content: |
          <?php
          // Simple LAMP workflow demonstration page
          $db_host = "{{ db_host }}";
          $db_user = "{{ db_user }}";
          $db_pass = "{{ db_pass }}";
          $db_name = "{{ db_name }}";
          $workflow = "{{ workflow_name }}";
          $hostname = gethostname();
          $timestamp = date("Y-m-d H:i:s");

          $conn = @new mysqli($db_host, $db_user, $db_pass, $db_name);
          $db_status = $conn->connect_error ? "Database connection failed" : "Database connected successfully";

          echo "<html><head><title>$workflow</title></head>
                <body style='font-family:Arial;margin:40px;'>
                <h2 style='color:#2d89ef;'>$workflow</h2>
                <p><strong>Host:</strong> $hostname</p>
                <p><strong>Database:</strong> $db_status</p>
                <p><strong>Application:</strong>Apache & PHP deployed successfully</p>
                <p><strong>Timestamp:</strong> $timestamp</p>
                <hr><small>Generated by AWX workflow demo</small>
                </body></html>";
          ?>

    - name: Write deployment marker
      copy:
        dest: /tmp/deploy_marker.txt
        content: "Workflow deployed on {{ inventory_hostname }} at {{ lookup('pipe','date +%Y-%m-%d_%H:%M:%S') }}"
