---
# deploy_app.yml
- name: Deploy Workflow Example Web App (Corrected)
  hosts: webservers
  become: yes
  gather_facts: false

  vars:
    # prefer group 'dev' then 'dbservers', fallback to localhost
    db_host: "{{ (groups['dev'] | default([]) + groups['dev'] | default([]) )[0] | default('127.0.0.1') }}"
    db_name: "myappdb"
    db_user: "appuser"
    db_pass: "AppUserPass!"
    workflow_name: "AWX Workflow Demo"

  tasks:
    - name: Install required packages (Ubuntu)
      apt:
        name:
          - apache2
          - php
          - libapache2-mod-php
          - php-mysql
          - mysql-client
          - netcat
        state: present
        update_cache: yes

    - name: Remove default Apache index.html if present
      file:
        path: /var/www/html/index.html
        state: absent

    - name: Deploy safe workflow demo index.php
      copy:
        dest: /var/www/html/index.php
        mode: '0644'
        content: |
          <?php
          $db_host = "{{ db_host }}";
          $db_user = "{{ db_user }}";
          $db_pass = "{{ db_pass }}";
          $db_name = "{{ db_name }}";

          $workflow = "{{ workflow_name }}";
          $hostname = gethostname();
          $timestamp = date("Y-m-d H:i:s");

          $mysqli = @mysqli_connect($db_host, $db_user, $db_pass, $db_name);
          if (!$mysqli || mysqli_connect_errno()) {
              $db_status = "❌ DB connection failed: " . mysqli_connect_error();
          } else {
              $db_status = "✅ DB connected successfully";
              $mysqli->close();
          }

          echo "<html><head><title>$workflow</title></head><body style='font-family:Arial;margin:30px;'>";
          echo "<h2 style='color:#2d89ef;'>$workflow</h2>";
          echo "<p><strong>Host:</strong> $hostname</p>";
          echo "<p><strong>DB Host:</strong> $db_host</p>";
          echo "<p><strong>DB Status:</strong> $db_status</p>";
          echo "<p><strong>Timestamp:</strong> $timestamp</p>";
          echo "<hr><small>Generated by AWX</small></body></html>";
          ?>

    - name: Ensure web directory ownership
      file:
        path: /var/www/html
        owner: www-data
        group: www-data
        recurse: yes

    - name: Get PHP major.minor version (if PHP installed)
      shell: php -r 'echo PHP_MAJOR_VERSION.".".PHP_MINOR_VERSION;' 2>/dev/null || true
      register: phpver_cmd
      changed_when: false
      failed_when: false

    - name: Try to enable PHP apache module for detected PHP version (best-effort)
      shell: |
        if [ -n "{{ phpver_cmd.stdout | default('') }}" ]; then
          a2enmod php{{ phpver_cmd.stdout }} >/dev/null 2>&1 || true
        fi
      args:
        executable: /bin/bash
      register: a2enmod_res
      changed_when: a2enmod_res.rc == 0 and (a2enmod_res.stdout | default('') != '' or a2enmod_res.stderr | default('') != '')
      failed_when: false

    - name: Restart Apache
      service:
        name: apache2
        state: restarted
        enabled: yes
