---
- name: Deploy Workflow Example Web App
  hosts: webserver
  become: yes
  gather_facts: false

  vars:
    db_host: "{{ groups['dev'][0] | default('127.0.0.1') }}"
    db_name: "myappdb"
    db_user: "appuser"
    db_pass: "AppUserPass!"
    workflow_name: "AWX Workflow Demo"

  tasks:
    - name: Install Apache and PHP
      apt:
        name:
          - apache2
          - php
          - libapache2-mod-php
          - php-mysql
        state: present
        update_cache: yes

    - name: Remove default Apache page
      file:
        path: /var/www/html/index.html
        state: absent

    - name: Deploy workflow demo page
      copy:
        dest: /var/www/html/index.php
        mode: '0644'
        content: |
          <?php
          $db_host = "{{ db_host }}";
          $db_user = "{{ db_user }}";
          $db_pass = "{{ db_pass }}";
          $db_name = "{{ db_name }}";
          $workflow = "{{ workflow_name }}";
          $hostname = gethostname();
          $timestamp = date("Y-m-d H:i:s");

          $conn = @new mysqli($db_host, $db_user, $db_pass, $db_name);
          $db_status = $conn->connect_error ? "❌ DB connection failed: " . $conn->connect_error : "✅ DB connected successfully";

          echo "<html><head><title>$workflow</title></head><body style='font-family:Arial;margin:30px;'>";
          echo "<h2 style='color:#2d89ef;'>$workflow</h2>";
          echo "<p><strong>Host:</strong> $hostname</p>";
          echo "<p><strong>DB Host:</strong> $db_host</p>";
          echo "<p><strong>DB Status:</strong> $db_status</p>";
          echo "<p><strong>Timestamp:</strong> $timestamp</p>";
          echo "<hr><small>Generated by AWX</small></body></html>";
          ?>

    - name: Ensure Apache running
      service:
        name: apache2
        state: restarted
        enabled: yes
