---
- name: Secure MariaDB (idempotent SQL approach)
  hosts: dev
  become: yes
  gather_facts: false
  vars:
    db_root_password: "RootPass123!"
    db_marker: /var/local/awx-db-secured

  tasks:
    - name: Ensure MariaDB service is installed and running
      apt:
        name:
          - mariadb-server
          - mariadb-client
        state: present
        update_cache: yes
    
    - name: Ensure mariadb service is started & enabled
      service:
        name: "{{ 'mariadb' if (ansible_facts['os_family'] == 'Debian') else 'mariadb' }}"
        state: started
        enabled: yes
    
    - name: Wait for MariaDB TCP port 3306 to be ready
      wait_for:
        host: 127.0.0.1
        port: 3306
        timeout: 60
        state: started
    
    - name: Ensure mysql client present (for CLI secure commands)
      apt:
        name: mariadb-client
        state: present
    
    - name: Check for DB secure marker
      stat:
        path: /var/local/awx-db-secured
      register: db_marker_stat
    
    - name: Secure MariaDB (idempotent SQL) -- run on DB host
      shell: |
        mysql --user=root <<'SQL'
        ALTER USER IF EXISTS 'root'@'localhost' IDENTIFIED BY '{{ db_root_password }}';
        DELETE FROM mysql.user WHERE User='';
        DROP DATABASE IF EXISTS test;
        DELETE FROM mysql.db WHERE Db='test' OR Db LIKE 'test\_%';
        FLUSH PRIVILEGES;
        SQL
      register: mysql_secure_out
      failed_when: mysql_secure_out.rc not in [0,1]  # allow rc==1 when ALTER USER returns warnings; adjust if needed
      changed_when: mysql_secure_out.rc == 0
      when: not db_marker_stat.stat.exists
    
    - name: Create db secure marker
      file:
        path: /var/local/awx-db-secured
        state: touch
      when: not db_marker_stat.stat.exists
