---
- name: Install and configure MariaDB (LAMP project)
  hosts: db
  become: yes
  vars:
    mysql_root_password: "" 
    app_db_name: lampdb
    app_db_user: lampuser
    app_db_password: lamppass
  tasks:
    - name: Install MariaDB server
      apt:
        name: mariadb-server
        state: present

    - name: Ensure MariaDB is enabled and running
      service:
        name: mariadb
        state: started
        enabled: yes

    - name: Create application database
      shell: mysql --batch --skip-column-names -e "CREATE DATABASE IF NOT EXISTS {{ app_db_name }};"

    - name: Create application DB user and grant privileges
      shell: >
        mysql --batch --skip-column-names -e
        "CREATE USER IF NOT EXISTS '{{ app_db_user }}'@'%' IDENTIFIED BY '{{ app_db_password }}';
         GRANT ALL PRIVILEGES ON {{ app_db_name }}.* TO '{{ app_db_user }}'@'%';
         FLUSH PRIVILEGES;"
      args:
        warn: false

  handlers:
    - name: restart mariadb
      service:
        name: mariadb
        state: restarted
