---
- name: Install and configure MariaDB (LAMP project)
  hosts: db
  become: yes
  vars:
    mysql_root_password: ""
    app_db_name: lampdb
    app_db_user: lampuser
    app_db_password: lamppass

  tasks:
    - name: Install MariaDB server
      apt:
        name: mariadb-server
        state: present

    - name: Ensure MariaDB is enabled and running
      service:
        name: mariadb
        state: started
        enabled: yes

    - name: Create application database
      community.mysql.mysql_db:
        name: "{{ app_db_name }}"
        state: present

    - name: Create application DB user and grant privileges
      community.mysql.mysql_user:
        name: "{{ app_db_user }}"
        password: "{{ app_db_password }}"
        priv: "{{ app_db_name }}.*:ALL"
        host: '%'
        state: present

  handlers:
    - name: restart mariadb
      service:
        name: mariadb
        state: restarted
