---
- name: Ensure MariaDB network access and app user
  hosts: dev
  become: true
  gather_facts: false
  vars:
    db_root_password: "RootPass123!"
    app_db_name: "myappdb"
    app_db_user: "appuser"
    app_db_pass: "AppUserPass!"
    bind_address: "0.0.0.0"

  tasks:
    - name: Ensure bind-address is configured for MariaDB
      lineinfile:
        path: /etc/mysql/mariadb.conf.d/50-server.cnf
        regexp: '^bind-address\s*='
        line: "bind-address = {{ bind_address }}"
        backup: yes
      notify: restart mariadb

    - name: Ensure UFW allows MySQL (if UFW installed)
      ufw:
        rule: allow
        proto: tcp
        port: 3306
      when: ansible_facts.packages is defined and ('ufw' in ansible_facts.packages)
      ignore_errors: true

    - name: Wait for mariadb to listen on 3306
      wait_for:
        host: 127.0.0.1
        port: 3306
        timeout: 20

    - name: Create application DB and remote user
      shell: |
        mysql <<'SQL'
        CREATE DATABASE IF NOT EXISTS {{ app_db_name }} CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci;
        CREATE USER IF NOT EXISTS '{{ app_db_user }}'@'%' IDENTIFIED BY '{{ app_db_pass }}';
        GRANT ALL PRIVILEGES ON {{ app_db_name }}.* TO '{{ app_db_user }}'@'%';
        FLUSH PRIVILEGES;
        SQL
      args:
        executable: /bin/bash

  handlers:
    - name: restart mariadb
      service:
        name: mariadb
        state: restarted
