---
- name: Secure MariaDB (idempotent SQL approach)
  hosts: dbservers
  become: yes
  gather_facts: false
  vars:
    db_root_password: "RootPass123!"
    db_marker: /var/local/awx-db-secured

  tasks:
    - name: Ensure mysql client is present
      apt:
        name: mariadb-client
        state: present
        update_cache: yes

    - name: Check if DB already secured (marker file)
      stat:
        path: "{{ db_marker }}"
      register: db_marker_stat

    - name: Secure MariaDB - set root password and remove test users
      shell: |
        mysql --user=root <<'SQL'
        ALTER USER IF EXISTS 'root'@'localhost' IDENTIFIED BY '{{ db_root_password }}';
        DELETE FROM mysql.user WHERE User='';
        DROP DATABASE IF EXISTS test;
        DELETE FROM mysql.db WHERE Db='test' OR Db LIKE 'test\_%';
        FLUSH PRIVILEGES;
        SQL
      changed_when: "'Query OK' in stdout or rc == 0"
      register: mysql_secure_out
      when: not db_marker_stat.stat.exists

    - name: Create marker file after securing DB
      file:
        path: "{{ db_marker }}"
        state: touch
      when: not db_marker_stat.stat.exists
