---
- name: Send summary notification
  hosts: 192.168.100.150
  gather_facts: false
  tasks:
    - name: Print workflow summary
      debug:
        msg: "LAMP stack deployment and health check completed successfully!"
