- name: Rollback LAMP changes
  hosts: all
  become: yes
  vars:
    index_path: /var/www/html/index.php
    index_backup: /var/www/html/index.php.bak
  tasks:
    - name: Stop apache on webservers
      service:
        name: apache2
        state: stopped
      when: "'webserver' in group_names"
      ignore_errors: yes

    - name: Remove apache and php packages
      apt:
        name:
          - apache2
          - php
          - libapache2-mod-php
          - php-mysql
        state: absent
        purge: yes
      when: true
