---
- hosts: "controller"
  become: yes
  tasks:
    - name: creating a pv for awx
      shell: |
        cat > awx.yml << EOF
        apiVersion: v1
        kind: PersistentVolume
        metadata:
          name: awx-pv
        spec:
          capacity:
            storage: 15Gi
          accessModes:
            - ReadWriteOnce
          persistentVolumeReclaimPolicy: Retain
          storageClassName: ""
          hostPath:
            path: "/tmp"
        EOF
    - name: apply the PV
      shell: kubectl apply -f awx-pv.yml
