---
- name: Install Apache and start the service
  hosts: eoc-node1
  become: yes
  tasks:
    - name: Install the required package
      ansible.builtin.apt:
        name: "{{ ansible_facts['ansible_local']['custom']['general']['package'] }}"
        state: present
        update_cache: yes

    - name: Start the service
      ansible.builtin.service:
        name: "{{ ansible_facts['ansible_local']['custom']['general']['service'] }}"
        state: "{{ ansible_facts['ansible_local']['custom']['general']['state'] }}"
        enabled: "{{ ansible_facts['ansible_local']['custom']['general']['enabled'] }}"
