---
- name: Demonstrate host vars in AWX
  hosts: webserver
  gather_facts: false
  tasks:
    - name: Show environment details
      debug:
        msg: "Host {{ inventory_hostname }} is running in {{ env }} environment as a {{ server_role }} server."
    - name: Show custom app message
      debug:
        msg: "{{ app_message }}"
    - name: Write message in a file
      become: yes
      copy:
        dest: /home/admin/vars.txt
        content: |
          {{ app_message }}
          Server role: {{ server_role }}
          Environment: {{ env }}
