---
- name: Collect info from all hosts
  hosts: all
  gather_facts: false
  tasks:
    - name: Generate message per host
      debug:
        msg: "Host {{ inventory_hostname }} in {{ env }} environment with role {{ server_role }}"
      register: host_message
    - name: Store message in a fact
      set_fact:
        collected_msg: "{{ host_message.msg }}"
        
- name: Combine outputs and write to a single file
  hosts: test
  gather_facts: false
  tasks:
    - name: Combine all host messages
      set_fact:
        combined_output: |
          {% for host in play_hosts %}
          {{ hostvars[host]['collected_msg'] }}
          {% endfor %}
    - name: Write combined output to file
      copy:
        dest: /tmp/all_hosts_output.txt
        content: "{{ combined_output }}"
