- name: Enable and start Apache2 service on ubuntu web servers
  hosts: webservers
  become: yes
  tasks:
    - name: Start service apache2, if not started
      ansible.builtin.service:
        name: apache2
        state: started
